buildscript {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
    }
}

plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'signing'
}

android {
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

version = "1.0.2"
group   = "org.whispersystems"

repositories {
    mavenCentral()
    google()
}

// New Maven publication configuration
publishing {
    publications {
        release(MavenPublication) {
            groupId = group
            artifactId = 'jobmanager'
            version = version
            
            artifact("$buildDir/outputs/aar/${project.getName()}-release.aar")

            pom {
                name = 'jobmanager'
                packaging = 'aar'
                description = 'Job Manager for Android'
                url = 'https://github.com/WhisperSystems/jobmanager'

                scm {
                    url = 'scm:git@github.com:WhisperSystems/jobmanager.git'
                    connection = 'scm:git@github.com:WhisperSystems/jobmanager.git'
                    developerConnection = 'scm:git@github.com:WhisperSystems/jobmanager.git'
                }

                licenses {
                    license {
                        name = 'GPLv3'
                        url = 'https://www.gnu.org/licenses/gpl-3.0.txt'
                        distribution = 'repo'
                    }
                }

                developers {
                    developer {
                        name = 'Moxie Marlinspike'
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = sonatypeRepo
            credentials {
                username = whisperSonatypeUsername
                password = whisperSonatypePassword
            }
        }
    }
}

signing {
    sign publishing.publications.release
}

// Local install task replacement
task installArchives(type: Copy) {
    dependsOn assemble
    from("$buildDir/outputs/aar/") 
    into("${System.properties['user.home']}/.m2/repository/${project.group.replace('.', '/')}/${project.name}/${version}")
}
