apply plugin: 'java'

ext.version_number     = "2.7.1"
ext.group_info         = "org.whispersystems"
ext.curve25519_version = "0.5.0"

sourceCompatibility = 1.17
targetCompatibility = 1.17
archivesBaseName = "signal-protocol-java"
version          = version_number
group            = group_info



sourceSets {
    test {
        java {
            srcDirs = ['src/test/java/', project(':tests').file('src/test/java')]
        }
    }
}

dependencies {
    implementation "org.whispersystems:curve25519-java:${curve25519_version}"
    implementation 'com.google.protobuf:protobuf-java:3.21.12'

    

    testImplementation ('junit:junit:4.13.2')
}


test {
    testLogging {
        events 'passed'
        showStandardStreams = true
    }

    include 'org/whispersystems/**'
}

