apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'signing'

sourceCompatibility = 1.7
archivesBaseName = "signal-protocol-java"
version          = version_number
group            = group_info

repositories {
    mavenCentral()
    mavenLocal()
}

sourceSets {
    test {
        java {
            srcDirs = ['src/test/java/', project(':tests').file('src/test/java')]
        }
    }
}

dependencies {
    compile "org.whispersystems:curve25519-java:${curve25519_version}"
    compile 'com.google.protobuf:protobuf-java:2.5.0'

    testCompile ('junit:junit:3.8.2')
}


test {
    testLogging {
        events 'passed'
        showStandardStreams = true
    }

    include 'org/whispersystems/**'
}

signing {
    required { has("release") && gradle.taskGraph.hasTask("uploadArchives") }
    sign configurations.archives
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            pom {
                name.set('signal-protocol-java')
                description.set('Signal Protocol cryptography library for Java')
                url.set('https://github.com/WhisperSystems/libsignal-android')

                scm {
                    url.set('scm:git@github.com:WhisperSystems/libsignal-android.git')
                    connection.set('scm:git@github.com:WhisperSystems/libsignal-android.git')
                    developerConnection.set('scm:git@github.com:WhisperSystems/libsignal-android.git')
                }

                licenses {
                    license {
                        name.set('GPLv3')
                        url.set('https://www.gnu.org/licenses/gpl-3.0.txt')
                        distribution.set('repo')
                    }
                }

                developers {
                    developer {
                        name.set('Moxie Marlinspike')
                    }
                }
            }
        }
    }
    repositories {
        maven {
            url = sonatypeRepo
            credentials {
                username = whisperSonatypeUsername
                password = whisperSonatypePassword
            }
        }
    }
}

task installArchives(type: Upload) {
    description "Installs the artifacts to the local Maven repository."
    configuration = configurations['archives']
    repositories {
        mavenDeployer {
            repository url: "file://${System.properties['user.home']}/.m2/repository"
        }
    }
}

task packageJavadoc(type: Jar, dependsOn: 'javadoc') {
    from javadoc.destinationDir
    classifier = 'javadoc'
}

task packageSources(type: Jar) {
    from sourceSets.main.allSource
    classifier = 'sources'
}

artifacts {
    archives(packageJavadoc) {
        type = 'javadoc'
    }

    archives packageSources
}

