plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
    withJavadocJar()
}

group = group_info
version = version_number
archivesBaseName = "signal-protocol-java"

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation "org.whispersystems:curve25519-java:${curve25519_version}"
    implementation 'com.google.protobuf:protobuf-java:3.21.12'

    testImplementation 'junit:junit:4.13.2'
}

test {
    testLogging {
        events 'passed'
        showStandardStreams = true
    }
    include 'org/whispersystems/**'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = archivesBaseName
            
            pom {
                name = 'signal-protocol-java'
                description = 'Signal Protocol cryptography library for Java'
                url = 'https://github.com/WhisperSystems/libsignal-android'
                
                scm {
                    url = 'scm:git@github.com:WhisperSystems/libsignal-android.git'
                    connection = 'scm:git@github.com:WhisperSystems/libsignal-android.git'
                    developerConnection = 'scm:git@github.com:WhisperSystems/libsignal-android.git'
                }

                licenses {
                    license {
                        name = 'GPLv3'
                        url = 'https://www.gnu.org/licenses/gpl-3.0.txt'
                        distribution = 'repo'
                    }
                }

                developers {
                    developer {
                        name = 'Moxie Marlinspike'
                    }
                }
            }
        }
    }
    
    repositories {
        maven {
            url = findProperty('sonatypeRepo') ?: ''
            credentials {
                username = findProperty('whisperSonatypeUsername') ?: ''
                password = findProperty('whisperSonatypePassword') ?: ''
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}

// Local install task replacement
task installArchives(type: Copy) {
    dependsOn publishToMavenLocal
    from("${buildDir}/publications/mavenJava")
    into("${System.getProperty('user.home')}/.m2/repository/${project.group.replace('.', '/')/${archivesBaseName}/${version}")
}