apply plugin: 'com.android.library'

archivesBaseName = "signal-protocol-android"
version          = version_number
group            = group_info

android {
    namespace "org.whispersystems.libsignal"
    compileSdkVersion 33

    sourceSets {
        androidTest {
            java.srcDirs = ['src/androidTest/java', project(':tests').file('src/test/java')]
        }
    }
}

dependencies {
    implementation "org.whispersystems:curve25519-android:${curve25519_version}"
    implementation (project(':java')) {
        exclude group: 'org.whispersystems', module: 'curve25519-java'
    }
}
